language: php
php:
- 7.2
before_script:
  - composer install
script: phpunit tests
deploy:
	provider: heroku
	app: project1-travis-joana
	on: master
	skip_cleanup: true
	api_key:
	secure: RNbPKUqsXG/SGxUFNj19E7GAK+TQ/AX3dzAK97gOCpvOA93wrrduUU5nTMdP3KByo3MsN7kr56Eld574labQML85P8UZnvWtRXK7iQK3Y1cJ/CbDwZW7+9JNW8sYxxcFHILcPsCoJik6v0OyHPRkdsOUeDAWmYtODSGqJDFFSKCOl5YCGq5wqAykIn7T0Bzrb1tYUMv8fNptfjN+VG6lyqxkxEUBkVZ0ZKEZhY95avGxfa45GihgnM6G485YXbVnyrJAMvL3Qbf2yg0TZ8sMO5u0Lil3ksT98Ewsl+GfyWfYXg6J39dyVeF8J9SVFpGGtTdMTwG0Ife/z1I7V0p/Y4fh0I5xuXdGfkWqa46kxDqMTGwVEQMDSKjepxRfz/fNmWYAiJtEqf1DdL2ZbPcIiaDcVX1WWuY7YZ1cqZ6LQRGXKuaEmFlnWO60y6+/558Q6mkbLR10jpM69z3+2PCtyzejMpOHA+c4MLzIww+mCWI8vv0PGBqHVnHucRTLXKAqjV1E4Mnx1oy5nSUuWX2uE10X0pr7GLexPgx3vvCY54oT3mF8PAtNgL0JF+Mx6769PlYIHHCPGbv6+atqyYIOJz/nQrrr37LOx2mdFN+IkMeJNyO8RvsXVdPXaW/fRKLPd9sMlwpWQF4w4kzSPzsi58rOvmtEzX3WGZx2qKy5low=
